name: Deploy Shopify Theme

on:
    pull_request:
      branches:
      - main
    push:
      branches:
      - main
jobs:
  shopify:
    name: Shopify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Shopify
        uses: pgrimaud/action-shopify@master
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE_URL: kinkaracowholesale.myshopify.com
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
          THEME_PATH: ./
